default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: WorkApp_development

test:
  <<: *default
  database: WorkApp_test

production:
  <<: *default
  database: WorkApp_production
  username: <%= ENV['WORKAPP_DATABASE_USER'] %>
  password: <%= ENV['WORKAPP_DATABASE_PASSWORD'] %>
